apis/urls.py
from django.urls import path
from rest_framework.schemas import get_schema_view
from apis import views

app_name = 'apis'

urlpatterns = [

    # api endpoint - list of doctors
     path('doctors/',
         views.doctor_list,
         name='doctor_list'),

    # api endpoint - list of booked appointments for a given doctor, year and week number
     path('list_booked_appointments/<int:doctor_id>/<int:year>/<int:week_number>/',
         views.booked_appointments_list,
         name='list_booked_appointments'),


    # api endpoint - book an apointment
     path('book_appointment/',
         views.book_appointment,
         name='book_appointment'),

    # api endpoint - confirm an apointment
     path('confirm_appointment/<int:appointment_id>/',
         views.confirm_appointment,
         name='confirm_appointment'),

    # api endpoint - to register
     path('register_patient',
         views.register_patient,
         name='register_patient'),

     
    # api endpoint - request daysoff
    path('request_daysoff/',
         views.request_daysoff,
         name='request_daysoff'),


    # api endpoint - add to wishlist
     path('add_to_wishlist/',
         views.add_to_wishlist,
         name='add_to_wishlist'),

    # API schema
     path('schema/',
         get_schema_view(
             title='Appointment REST API',
             description='API for interacting with online booking appointment system.',
             version='1.0'
         ),
         name='schema_view'),
]

appointments_app/urls.py
from django.urls import path
from . import views


app_name = 'appointments_app'


urlpatterns = [

    # generate and show a list of doctors
    path('doctors/', views.doctor_list_view, name='doctor_list_view'),

    # return week calendar webpage for a given doctor for current week with next
    # and previous week buttons
    path('<int:doctor_id>/', views.appointment_view, name='appointment_view'),

    # generate and send week calendar --this url is to be accessed via
    # XMLHttpRequest from the week_calendar.html webpage
    path('calendar/<int:doctor_id>/<int:year>/<int:week_number>/',
         views.send_week_calendar,
         name='send_week_calendar'),

    # book an appointment
    path('book/', views.book_appointment, name='book_appointment'),

    # cancel an appointment
    path('cancel/', views.cancel_appointment, name='cancel_appointment'),

     # confirm an appointment
    path('confirm/', views.confirm_appointment, name='confirm_appointment'),

    # request daysoff
    path('request_daysoff/', views.request_daysoff, name='request_daysoff'),

    # cancel daysoff
    path('cancel_daysoff/<int:pk>/', views.cancel_daysoff, name='cancel_daysoff'),

     # book an appointment
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
]

oabs_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users_app.urls')),
    path('appointment/', include('appointments_app.urls')),
    path('api/', include('apis.urls')),
    path('admin/', admin.site.urls),
]

appointments_app/forms.py
from django import forms
from django.forms import ModelForm
from appointments_app.models import Appointment
from appointments_app.models import DaysOff
from appointments_app.models import WishList


class BookNewAppointment(ModelForm):
    ''' This form is for valdation data for booking appointment '''

    class Meta:
        model = Appointment
        fields = ['doctor', 'appointment_date', 'symptoms']


class CancelAppointment(ModelForm):
    ''' This form is for valdation data for cancelling appointment '''

    class Meta:
        model = Appointment
        fields = ['doctor', 'appointment_date']


class ConfirmAppointment(ModelForm):
    ''' This form is for data validation for cancelling appointment '''

    class Meta:
        model = Appointment
        fields = ['patient', 'appointment_date']

    
class RequestDaysOffForm(ModelForm):
    ''' Days off form'''
   
    class Meta:
        model = DaysOff
        fields = ['date_from', 'date_till']


class AddToWishList(ModelForm):
    ''' This form is for valdation data for booking appointment '''

    class Meta:
        model = WishList
        fields = ['doctor', 'appointment_date', 'symptoms']

appointments_app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.http import HttpResponseNotAllowed
from django.http import HttpResponseNotFound
from isoweek import Week
from .calendar_html import WeekAppointmentCalendar
from datetime import timedelta
from datetime import datetime, time
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db import IntegrityError
from django.db.models import Q
from datetime import datetime
from . import models
from users_app.models import Patient
from users_app.models import Doctor
from . import forms


@login_required(login_url='users_app:login_page')
def doctor_list_view(request):
    ''' Show list of doctors with buttons to book appointments'''

    query_set = Doctor.objects.only('user')
    return render(
        request, "list_doctors.html",
        context={'doctors_list': query_set}
    )


@login_required(login_url='users_app:login_page')
def appointment_view(request, doctor_id):
    ''' return week calendar webpage for a given doctor for current 
    week with next and previous week buttons'''

    # determine today date
    day = datetime.now()

    # get the weekday
    weekday = datetime.now().isoweekday() 
    
    # if today is Saturday or Sunday then take the next monday as the current date
    if weekday == 6 or weekday ==7:
        day += timedelta(days=8 - day.isoweekday())

    # get the week number
    week_number = day.isocalendar().week

    # get the year
    year = day.year   

    try:
        query_set = Doctor.objects.get(pk=doctor_id)
        first_name = query_set.user.first_name
        last_name = query_set.user.last_name
        doctor_name = "Dr. " + first_name + " " + last_name

    except Doctor.DoesNotExist:
        return HttpResponseNotFound("Error: Doctor_id not found.")

    except Exception:
        return HttpResponseNotFound("Error: something wrong")

    return render(request, 'week_calendar.html', context={
        "doctor_id": doctor_id,
        "doctor_name": doctor_name,
        "year": year,
        "week_number": week_number,
    })


@login_required(login_url='users_app:login_page')
def send_week_calendar(request, doctor_id, year, week_number):
    ''' # generate and send week calendar --this url is to be accessed 
    via XMLHttpRequest from the week_calendar.html webpage '''

    # Here the doctor_id needs to be checked to confirm that it exists

    # get the date for the start and end for the given week
    w = Week(year, week_number)
    week_start_date = w.monday()
    week_end_date = w.sunday()

    weekAppointmentCal = WeekAppointmentCalendar(

        appointment_duration_minutes=timedelta(hours=0, minutes=20, seconds=0),
        opening_hours_from=time(7, 0, 0),
        opening_hours_till=time(17, 0, 0)
    )

    try:
        # the user may be not found in the Patient table either because this patient does not exist (geniun error)
        # or because the logged user is a doctor
        patient_id = Patient.objects.get(user=request.user).pk

    except Patient.DoesNotExist:

        try:
            # checking if the current user is a doctor?
            Doctor.objects.get(user=request.user)
            # when the logged-in user is a docotr we set the patient_id to -100 for the correct
            # color of cells determination in the week calendar
            patient_id = '-100'
        except Doctor.DoesNotExist:
            return HttpResponseNotFound("Error: User_id not found.")

        except Exception:
            return HttpResponseNotFound("Error: something wrong")

    # calendar._generateOneDayColumn('17')
    week_html_table = weekAppointmentCal.generate(
        patient_id,
        doctor_id,
        week_start_date,
        week_end_date
    )

    return HttpResponse(week_html_table, content_type="text/html", status=200)


@login_required(login_url='users_app:login_page')
def book_appointment(request):

    if request.method != 'POST':
        return HttpResponseNotAllowed(('POST',))

    form = forms.BookNewAppointment(request.POST)

    if not form.is_valid():
        messages.error(request, "Error: " + form.errors)
        return HttpResponseRedirect(reverse("appointment_view"))

    try:
        patient = Patient.objects.get(user=request.user)
        #patient_id = patient.pk

    except Patient.DoesNotExist:
        return HttpResponseNotFound("Error: You are not registered as a patient.")

    except Exception:
        return HttpResponseNotFound("Error: something wrong")

    try:
        new_appointment = form.save(commit=False)
        new_appointment.patient = patient
        new_appointment.save()

    except IntegrityError:
        messages.error(request, "Error: DB Integrity error ")

    doctor_id = form.cleaned_data['doctor'].pk
    appointment_date = form.cleaned_data['appointment_date']


    # now when a new appointment is booked we need to check whether 
    # this appointment was in the the waiting list for the current user
    # and possibly other users
    wishlist = models.WishList.objects.filter(
            Q(doctor=doctor_id),
            Q(appointment_date=appointment_date),
            Q(wishlist_status="Available"))
        
    
    waiting_status = models.WishListStatus.objects.get(status="Waiting")
    booked_status = models.WishListStatus.objects.get(status="Booked")
        
        
    # set 'waiting' status for all the rest patients who might have 
    # this time slot in their wish lists
    for entry in wishlist:
        if entry.patient.user == request.user:
            # this is the case when the current user had this timeslot in their 
            # wish list and they have just booked it
            entry.wishlist_status= booked_status
        else:
            # for all the rest patient set to 'waiting ' again
            entry.wishlist_status= waiting_status
        entry.save()


    return HttpResponseRedirect(reverse("appointments_app:appointment_view", args=(doctor_id,)))

    
@login_required(login_url='users_app:login_page')
def cancel_appointment(request):
    ''' Cancel appointment'''

    if request.method != 'POST':
        return HttpResponseNotAllowed(('POST',))

    form = forms.CancelAppointment(request.POST)

    if not form.is_valid():
        messages.error(request, "Error: " + form.errors)
        return HttpResponseRedirect(reverse("appointment_view"))

    try:
        patient = Patient.objects.get(user=request.user)
        doctor = form.cleaned_data['doctor']
        appointment_date = form.cleaned_data['appointment_date']
        cancelled_status = models.AppointmentStatus.objects.get(
            status='Cancelled_by_patient')

        appointment = models.Appointment.objects.get(
            Q(patient=patient),
            Q(doctor=doctor),
            Q(appointment_date=appointment_date),
            Q(appointment_status="Confirmed") | Q(
                appointment_status="Requested")
        )

        appointment.appointment_status = cancelled_status
        appointment.save()


        # now we ned to check if the cancelled appointment was added to 
        # wish list by someone else

        wishlist = models.WishList.objects.filter(
            Q(doctor=doctor),
            Q(appointment_date=appointment_date),
            Q(wishlist_status="Waiting"))
        
        available_status = models.WishListStatus.objects.get(status="Available")
        
        
        for entry in wishlist:
            entry.wishlist_status= available_status
            entry.save()

    except models.AppointmentStatus.DoesNotExist:
        return HttpResponseNotFound("Error: Appointment status does not exist.")

    except models.Appointment.DoesNotExist:
        return HttpResponseNotFound("Error: Appointment does not exist in the db")

    except Patient.DoesNotExist:
        return HttpResponseNotFound("Error: You are not registered as a patient.")

    except Exception:
        return HttpResponseNotFound("Error: something wrong")

    return HttpResponseRedirect(reverse("appointments_app:appointment_view", args=(doctor.pk,)))


@login_required(login_url='users_app:login_page')
def confirm_appointment(request):
    ''' This is for doctors to confirm appointment'''

    if request.method != 'POST':
        return HttpResponseNotAllowed(('POST',))

    try:
        # checking if the current user is a doctor - only doctors can confirm appointments
        Doctor.objects.get(user=request.user)
    except Doctor.DoesNotExist:
        return HttpResponseNotFound("Error: current user is not a doctor -- appointment cannot be confirmed.")

    form = forms.ConfirmAppointment(request.POST)

    if not form.is_valid():
        messages.error(request, "Error: " + f'{form.errors}')
        return HttpResponseRedirect(reverse("users_app:home_page"))

    try:
        patient = form.cleaned_data['patient']
        doctor = Doctor.objects.get(user=request.user)
        appointment_date = form.cleaned_data['appointment_date']
        confirmed_status = models.AppointmentStatus.objects.get(
            status='Confirmed')

        appointment = models.Appointment.objects.get(
            Q(patient=patient),
            Q(doctor=doctor),
            Q(appointment_date=appointment_date),
            Q(appointment_status="Requested")
        )

        appointment.appointment_status = confirmed_status
        appointment.save()

    except models.AppointmentStatus.DoesNotExist:
        return HttpResponseNotFound("Error: Appointment status does not exist.")

    except models.Appointment.DoesNotExist:
        return HttpResponseNotFound("Error: Appointment does not exist in the db")

    except models.Doctor.DoesNotExist:
        return HttpResponseNotFound("Error: Doctor does not exist in the db")

    except Patient.DoesNotExist:

appointments_app/templates/list_doctors.html
{% extends "./base.html" %}

{% block title %} List of Doctors {% endblock %}

{% block nav %} 
{% include "./nav_patient.html" %}
{% endblock %}

{% block content %}

<div class="row">
    <p2> List of Doctors </p2>
</div>


    {% for doctor in doctors_list %}
    <div class="row mt-3">

        <div class="col">

        </div>

        <div class="col">
            Dr. {{ doctor.user.first_name }} {{ doctor.user.last_name }}
        </div>
        
        <div class="col">
            <button type="button" class="btn btn-primary" onclick="onClick('{{ doctor.pk }}', this)">Book Appointment</button>
        </div>
        <div class="col">
            
        </div>
    </div>
    {% endfor %}


<script>
    var onClick = function(doctor_id,object) {      
        //adopted from here https://stackoverflow.com/questions/73436370/django-button-redirecting-to-url-index
        //https://stackoverflow.com/questions/17832194/get-javascript-variables-value-in-django-url-template-tag
        
        document.location.href = "{% url 'appointments_app:appointment_view' 999 %}".replace('999', doctor_id);
            };

</script>

{% endblock %}

appointments_app/templates/request_daysoff.html
{% extends "./base.html" %}

{% block title %} Request Days off {% endblock %}

{% block nav %}
{% include "./nav_doctor.html" %}
{% endblock %}

{% block content %}

{% if messages %}

{% for message in messages %}

{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}

<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endif %}

{% endfor %}

{% endif %}

<script>

    function checkform() {

        // this is manual form check

        let form = document.getElementById("date_form");

        let date_from = document.getElementById("date_from").value;
        let date_till = document.getElementById("date_till").value;

        if (date_from == "" || date_from == "") {
            alert("Please enter the date From and To");
            return false;
        }

        date_from = Date.parse(date_from);
        date_till = Date.parse(date_till);

        if (date_from > date_till) {
            alert("The datetime From should be less than datetime To");
            return false;
        }

        form.submit();

    };

</script>


<script>
    var onClick = function (daysoff_id, object) {

        if (confirm("Are sure you want to cancel your days off?")) {
            //adopted from here https://stackoverflow.com/questions/73436370/django-button-redirecting-to-url-index
            // https://stackoverflow.com/questions/17832194/get-javascript-variables-value-in-django-url-template-tag
        document.location.href = "{% url 'appointments_app:cancel_daysoff' 999 %}".replace('999', daysoff_id);
        } else {
            return false;
        }
        
    };


</script>


<div class="row mt-3">
    <nav class="navbar navbar-light ">
        <div class="container-fluid">
            <span class="navbar-brand mb-1 h1">Days off</span>
        </div>
    </nav>

</div>

<div class="row mt-3">


    <div class="col  justify-content-center text-center">

        <div class="row mt-3">
            <nav class="navbar navbar-light ">
                <div class="container-fluid justify-content-center text-center">
                    <span class="navbar-brand mb-1 ">Book Days off</span>
                </div>
            </nav>

        </div>

        <form id='date_time_form' method='post'>

            {% csrf_token %}

            <p>
            <div class="form-group">
                <label for="date_from">From: </label> <br>
                <input type="date" id="date_from" name="date_from" required />
            </div>
            </p>

            <p>
            <div class="form-group">
                <label for="date_till">To: </label> <br>
                <input type="date" id="date_till" name="date_till" required />
            </div>
            </p>

            <button type="submit" class="btn btn-primary" onclick="return checkform();">Submit</button>

        </form>
    </div>

    <div class="col justify-content-center text-center">

        <nav class="navbar navbar-light ">
            <div class="container-fluid justify-content-center text-center">
                <span class="navbar-brand mb-1 ">List of Booked Days off</span>
            </div>
        </nav>

        <table class="table">

            <thead>
                <tr>
                    <th scope="col">From</th>
                    <th scope="col">TO</th>
                    <th scope="col">status</th>
                    <th scope="col"></th>

                </tr>
            </thead>


            <tbody>
                {% for dayoff in daysoff_list %}
                <tr>
                    <td>{{ dayoff.date_from }}</td>
                    <td>{{ dayoff.date_till }}</td>
                    <td>{{ dayoff.daysoff_status }}</td>

                    
                    {% if dayoff.daysoff_status.status != "Cancelled" %}

                    <td>
                        <button type="button" class="btn btn-primary"
                            onclick="onClick('{{ dayoff.pk }}', this)">Cancel</button>
                            
                    </td>
                    
                    {% endif %}
                    
                    

                </tr>
                {% endfor %}
            </tbody>

        </table>

    </div>
</div>




{% endblock %}

appointments_app/templates/week_calendar.html
{% extends "./base.html" %}

{% block title %} Calendar_test {% endblock %}

{% block nav %} 
{% include "./nav_patient.html" %}
{% endblock %}

{% block content %}

{% if messages %}

{% for message in messages %}

{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

<div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}

<div class="alert alert-success alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

{% endif %}

{% endfor %}

{% endif %}

<div class="row">
    <nav class="navbar navbar-light">
        <div class="container-fluid">
            <span class="navbar-brand h1">{{ doctor_name }}</span>
        </div>
    </nav>
</div>

<div class="row">

    <div class="btn-group" role="group">
        <div class="col">
            <button type="button" class="btn btn-success float-start btn-lg" id="btnPreviousWeek">&#x3c;&#x3c; Previous
                Week</button>
        </div>

        <div class="col">
            <button type="button" class="btn btn-success float-end btn-lg" id="btnNextWeek"> &ensp; &ensp;Next Week
                &#x3e;&#x3e;</button>
        </div>
    </div>

</div>

<div class="row">

    <table class='table' id='table_calendar'></table>
</div>

<!-- Adopted from https://getbootstrap.com/docs/5.0/components/modal/ -->
<!-- Modal window-->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex=">
    aria-labelledby=" staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <form action="None" method="post" name="modalForm">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalFormTitle">Title_none</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal_body">
                    No text
                </div>
                <!-- Textarea for entering symptoms -->
                <div class="modal-body" id="modal_symptoms">                    
                </div>
                <div class="modal-footer" id="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close window</button>
                    <input type="hidden" name="doctor" value={{ doctor_id }} />                    
                    <button type="submit" class="btn btn-primary" id="modalFormSubmitButton">None</button>
                </div>
            </div>
        </form>
    </div>
</div>


<!-- A JavaScript date library for parsing, validating, manipulating, and formatting dates. -->
<script src="https://cdn.jsdelivr.net/npm/moment@2.29.4/moment.min.js"></script>



<script>

    // Table cell onClick event listener
    function onCellClick(e) {

        const cell = e.target.closest('td');

        // store the colour of the current cell
        colour_cell = '';


        if (!cell) {
            return;
        }

        if (cell.className == 'table-success') {
            console.log("Green cell");
            colour_cell = 'green';
        } else if (cell.className == 'table-secondary') {
            console.log("Gray cell");
            return;
        } else if (cell.className == 'table-danger') {
            console.log("Red cell - no booking possible, however it is possible to add this timeslot into wish list");
            colour_cell = 'red';
        // Blue cell
        } else if (cell.className =='table-primary'){
            console.log("Blue cell");
            colour_cell = 'blue';

        } else if (cell.className =='table-warning'){
            console.log("yellow cell");
            colour_cell = 'yellow';

        }else{
            console.log("onCellClick - cell has no colour or colour is unknown.");
            return;
        }            

        // reading date and time from data-date attribute
        const data_date = cell.dataset.date;

        // get body element from the modal dialog and add text
        const mbody = document.getElementById('modal_body');
        mbody.innerHTML = '<h6>' + '{{ doctor_name }}' + '</h6>' + '<p>' + data_date + '</p>';

        // Adding appointment date and time as a hidden input to be sent to the server
        const modalfooter = document.getElementById('modal-footer');
        modalfooter.innerHTML += "<input type='hidden' id='appointment_date' name='appointment_date' value= " + "'" + data_date + "'" + " />";

        // depending on the cell colour we define the behaviour of the modal window
        if (colour_cell == 'green'){

            // patient can book an appointment for the green timeslots 
            document.modalForm.action = "{% url 'appointments_app:book_appointment' %}";
            const submit_button = document.getElementById('modalFormSubmitButton');
            submit_button.innerText ='Book';

            // update modal window title
            const form_title = document.getElementById('modalFormTitle');
            form_title.innerText ='Book appointment?';
            
            // add symptom text box with a lable  
            const msymptoms = document.getElementById('modal_symptoms');
            msymptoms.innerHTML = "<h6>Enter your symptoms here: </h6>";
            msymptoms.innerHTML += "<textarea id='symptoms' name='symptoms' rows='4' cols='44' required></textarea>"                              

        } else if (colour_cell == 'blue' || colour_cell == 'yellow'){

            // patient can cancel the appointment for the blue timeslots

            // update the url in the form to one that allows to cancel an appointment 
            // and update modal window labels 
            document.modalForm.action = "{% url 'appointments_app:cancel_appointment' %}";
            const submit_button = document.getElementById('modalFormSubmitButton');
            submit_button.innerText ='Cancel Appointment';
            
            //update title of modal window
            const form_title = document.getElementById('modalFormTitle');
            form_title.innerText ='Cancel appointment?';

        } else if (colour_cell == 'red'){

            // patient can add this timeslot into wish list
            document.modalForm.action = "{% url 'appointments_app:add_to_wishlist' %}";
            const submit_button = document.getElementById('modalFormSubmitButton');
            submit_button.innerText ='Add to Wish List';

            // update modal window title
            const form_title = document.getElementById('modalFormTitle');
            form_title.innerText ='Add to wish list?';
            
            // add symptom text box with a lable  
            const msymptoms = document.getElementById('modal_symptoms');
            msymptoms.innerHTML = "<h6>Enter your symptoms here: </h6>";
            msymptoms.innerHTML += "<textarea id='symptoms' name='symptoms' rows='4' cols='44' required></textarea>"           

        } else {
            console.log('onCellClick -- Error something wrong colour is not defined. ');
            return;
        }

        var myModal = new bootstrap.Modal(document.getElementById('staticBackdrop'), {
            keyboard: false
        });

        // show modal window
        myModal.show();
    };

    // this is called as a callback to assign event listeners for html-table cells
    function addEventListeners() {

        const day_columns = document.getElementsByClassName('table table-hover one-day-column');

        for (var i = 0; i < day_columns.length; i++) {
            day_columns[i].addEventListener("click", onCellClick);
        }
    };



</script>

<script>

    // update week calendar  
    function update_calendar(doctor_id, year, week_number, mycallback) {
        const request = new XMLHttpRequest();
        request.open('GET', '/appointment/calendar/' + doctor_id + '/' + year + '/' + week_number + '/');
        request.send();

        request.onload = function () {
            if (request.status == 200) {
                let table = document.getElementById('table_calendar');
                table.innerHTML = request.response;
                mycallback();
            }
        };

        return true;
    };

    // return a number of isoweeks in the sent year
    function get_number_of_weeks(year) {

        const year_js = moment().year(year);
        return year_js.weeksInYear();
    };

    // increment week number by one and update calendar
    function increment_week_number() {

        year = parseInt(sessionStorage.getItem("year"), 10);
        week_number = parseInt(sessionStorage.getItem("week_number"), 10);

        week_number += 1;

        const number_of_weeks = get_number_of_weeks(year);

        if (week_number > number_of_weeks) {

            // if the incremented week does not exist in the current year then we need to switch
            // to the first week of the next year

            year += 1;
            sessionStorage.setItem("year", year);

            week_number = 1;
        }

        sessionStorage.setItem("week_number", week_number);

        update_calendar({{ doctor_id }}, year, week_number, addEventListeners);

    return true;
    };

    // decrement week number by one and update calendar
    function decrement_week_number() {

        year = parseInt(sessionStorage.getItem("year"), 10);
        week_number = parseInt(sessionStorage.getItem("week_number"), 10);


        // special care needs to be taken when the current week is one and we are going to decrement this
        if (week_number == 1) {

            // we need to decrement the year as week 0 does not exist
            year -= 1;

            //we need to check how many weeks are in the decremented year
            let number_of_weeks = get_number_of_weeks(year);

            // and assign this number to the week counter
            week_number = number_of_weeks;

        } else {

            // just decrement when we are no in the edge
            week_number -= 1;

        }

        sessionStorage.setItem("year", year);
        sessionStorage.setItem("week_number", week_number);

        update_calendar({{ doctor_id }}, year, week_number, addEventListeners);

    return true;
    };

</script>

<script>

    // store the original values for year and week_number passed into the template    
    sessionStorage.setItem("year", {{ year }});
    sessionStorage.setItem("week_number", {{ week_number }});


    // declaration for the event listener for Next week button
    document.getElementById("btnNextWeek").addEventListener("click", function () {

        increment_week_number();

        // https://stackoverflow.com/questions/72494154/a-listener-indicated-an-asynchronous-response-by-returning-true-but-the-messag
        return true;

    });


    // declaration for the event listener for Previous week button
    document.getElementById("btnPreviousWeek").addEventListener("click", function () {

        decrement_week_number();

        // https://stackoverflow.com/questions/72494154/a-listener-indicated-an-asynchronous-response-by-returning-true-but-the-messag
        return true;

    });

</script>


<script>

    document.onload = update_calendar({{ doctor_id }}, {{ year }}, {{ week_number }}, addEventListeners);

</script>

{% endblock %}