apis/urls.py
from django.urls import path
from rest_framework.schemas import get_schema_view
from apis import views

app_name = 'apis'

urlpatterns = [

    # api endpoint - list of doctors
     path('doctors/',
         views.doctor_list,
         name='doctor_list'),

    # api endpoint - list of booked appointments for a given doctor, year and week number
     path('list_booked_appointments/<int:doctor_id>/<int:year>/<int:week_number>/',
         views.booked_appointments_list,
         name='list_booked_appointments'),


    # api endpoint - book an apointment
     path('book_appointment/',
         views.book_appointment,
         name='book_appointment'),

    # api endpoint - confirm an apointment
     path('confirm_appointment/<int:appointment_id>/',
         views.confirm_appointment,
         name='confirm_appointment'),

    # api endpoint - to register
     path('register_patient',
         views.register_patient,
         name='register_patient'),

     
    # api endpoint - request daysoff
    path('request_daysoff/',
         views.request_daysoff,
         name='request_daysoff'),


    # api endpoint - add to wishlist
     path('add_to_wishlist/',
         views.add_to_wishlist,
         name='add_to_wishlist'),

    # API schema
     path('schema/',
         get_schema_view(
             title='Appointment REST API',
             description='API for interacting with online booking appointment system.',
             version='1.0'
         ),
         name='schema_view'),
]

appointments_app/urls.py
from django.urls import path
from . import views


app_name = 'appointments_app'


urlpatterns = [

    # generate and show a list of doctors
    path('doctors/', views.doctor_list_view, name='doctor_list_view'),

    # return week calendar webpage for a given doctor for current week with next
    # and previous week buttons
    path('<int:doctor_id>/', views.appointment_view, name='appointment_view'),

    # generate and send week calendar --this url is to be accessed via
    # XMLHttpRequest from the week_calendar.html webpage
    path('calendar/<int:doctor_id>/<int:year>/<int:week_number>/',
         views.send_week_calendar,
         name='send_week_calendar'),

    # book an appointment
    path('book/', views.book_appointment, name='book_appointment'),

    # cancel an appointment
    path('cancel/', views.cancel_appointment, name='cancel_appointment'),

     # confirm an appointment
    path('confirm/', views.confirm_appointment, name='confirm_appointment'),

    # request daysoff
    path('request_daysoff/', views.request_daysoff, name='request_daysoff'),

    # cancel daysoff
    path('cancel_daysoff/<int:pk>/', views.cancel_daysoff, name='cancel_daysoff'),

     # book an appointment
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
]

oabs_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users_app.urls')),
    path('appointment/', include('appointments_app.urls')),
    path('api/', include('apis.urls')),
    path('admin/', admin.site.urls),
]

users_app/urls.py
from django.urls import path
from . import views

app_name = 'users_app'

urlpatterns = [   
    
    path('', views.login_view, name='login_page'),
    path('logout/', views.logout_view, name='logout_page'),
    path('registration/', views.registration_view, name='registration_page'),
    path('home/', views.home_view, name='home_page'),

]

users_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Data seeding: two groups of users have to be created namely  doctors and patients

class Patient(models.Model):
    ''' Store the patient details'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dob = models.DateField(blank=False)
    home_address = models.CharField(max_length=256, blank=False)
    home_phone = models.CharField(max_length=20, blank=False)
    
    # set to false by default as medical staff should confirm registration
    registered_status = models.BooleanField(default=False, blank=False)

    def __str__(self):
        return f'{self.user.username}'


class DoctorType(models.Model):
    """ Doctor's specialisation"""
    type = models.CharField(max_length=100, null=False)

    # Data seeding: GP, paediatrician

    def __str__(self):
        return f'{self.type}'


class Doctor(models.Model):
    '''Store doctor details'''
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    type = models.ForeignKey(DoctorType, on_delete=models.PROTECT)
    licence_valid = models.BooleanField(blank=False)
    dob = models.DateField(blank=False)
    home_address = models.CharField(max_length=256, blank=False)
    home_phone = models.CharField(max_length=20, blank=False)

    def __str__(self):      
        return f'{self.user.username}'

users_app/forms.py
from django import forms
from django.contrib.auth.models import User

from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    ''' Login form used in the login view'''
    username = forms.CharField(max_length=150)
    password = forms.CharField(max_length=150, widget=forms.PasswordInput)


class RegistrationForm(UserCreationForm):
    ''' Registration form'''

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = None
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None

    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    dob = forms.DateField()
    home_address = forms.CharField(
        max_length=256, widget=forms.Textarea(attrs={"rows": "5"}))
    home_phone = forms.CharField(max_length=20)

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'first_name',
                  'last_name', 'dob', 'home_address', 'home_phone')
        labels = {'first_name': 'First name:', 'last_name': 'Last name:',
                  'dob': 'Date of Birth:', 'home_address': 'Home address:', 'home_phone': 'Home phone:', }

        

users_app/views.py
from datetime import datetime
from datetime import timedelta
from django.shortcuts import render
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.http import HttpResponseNotFound
from .models import Patient, Doctor
from appointments_app.models import Appointment
from appointments_app.models import WishList
from django.contrib.auth.models import Group
from . import forms


def registration_view(request):
    ''' Patient registration view'''

    if request.method == 'POST':
        form = forms.RegistrationForm(request.POST)
        if form.is_valid():
            try:
                user = form.save()

                # adding a new user to a 'patients' group
                patients_group = Group.objects.get(name='patients')
                user.groups.add(patients_group)

                user.save()

                # adding new user to patient table
                patient = Patient(
                    user=user,
                    dob=form.cleaned_data['dob'],
                    home_address=form.cleaned_data['home_address'],
                    home_phone=form.cleaned_data['home_phone'])

                patient.save()

            except Exception:
                messages.error(
                    request, "Sorry, there was a problem during registration process. ")
                return HttpResponseRedirect(reverse("users_app:registration_page"))

            messages.success(request, "Your registration has been successful.")
            return HttpResponseRedirect(reverse("users_app:login_page"))

    else:
        form = forms.RegistrationForm()

    return render(request, 'registration.html', {'registration_form': form})


def login_view(request):
    ''' User login view'''

    if request.method == 'POST':
        form = forms.LoginForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password'],
            )

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse("users_app:home_page"))
                else:
                    messages.error(
                        request, "Sorry, your account is not active.")

            else:
                messages.error(
                    request, "The entered either login or password is invalid. ")
    else:
        form = forms.LoginForm()

    return render(request, 'login.html', {'login_form': form})


@login_required(login_url='users_app:login_page')
def logout_view(request):
    ''' Logout view provides the logout functionality'''
    logout(request)

    messages.success(request, "You are successfully logged out.")
    return HttpResponseRedirect(reverse("users_app:login_page"))


@login_required(login_url='users_app:login_page')
def home_view(request):
    ''' Serve the home page for users depending on the group they belongs to'''

    # user belongs to "patients" group
    if request.user.groups.filter(name='patients').exists():

        try:
            patient = Patient.objects.get(user=request.user)
            appointments = Appointment.objects.filter(
                patient=patient).order_by('-appointment_date')[:20]
            wishlist = WishList.objects.filter(
                patient=patient).order_by('-appointment_date')[:20]

        except Patient.DoesNotExist:
            return HttpResponseNotFound("Error: Patient_id not found.")

        except Exception:
            return HttpResponseNotFound("Error: DB error .")

        return render(request,
                      'home_patient.html',
                      context={'user': request.user,
                               'appointments': appointments,
                               'wishlist': wishlist})

    # user belongs to "doctors" group
    elif request.user.groups.filter(name='doctors').exists():

        # return week calendar webpage for a given doctor for current
        # week with next and previous week buttons       

        # determine today date
        day = datetime.now()

        # get the weekday
        weekday = datetime.now().isoweekday() 
        
        # if today is Saturday or Sunday then take the next monday as the current date
        if weekday == 6 or weekday ==7:
            day += timedelta(days=8 - day.isoweekday())

        # get the week number
        week_number = day.isocalendar().week

        # get the year
        year = day.year   

        doctor = request.user

        try:
            query_set = Doctor.objects.get(user=doctor)
            first_name = query_set.user.first_name
            last_name = query_set.user.last_name
            doctor_name = "Dr. " + first_name + " " + last_name

        except Doctor.DoesNotExist:
            return HttpResponseNotFound("Error: Doctor_id not found.")

        except Exception:
            return HttpResponseNotFound("Error: something wrong")

        return render(request, 'home_doctor.html', context={
            "doctor_id": query_set.pk,
            "doctor_name": doctor_name,
            "year": year,
            "week_number": week_number,
        })

    # something wrong - no group assigned to user
    else:
        return HttpResponseNotFound('<h1>No group assigned to the user</h1>')

users_app/templates/base.html
<!DOCTYPE html>

<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <meta name="keywords" content="appointment, medical, online, booking, surgery">
    <meta name="description" content="OABS Final Project">
    <meta name="author" content="AR">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>
</head>

<body>

    <div class="container">
        

        {% block nav %} There is no content rendered {% endblock %}       
        
        {% block content %} There is no content rendered {% endblock %}


        <footer>
            <div class="text-center p-3 mt-5 bg-light">
                © 2023 Copyright
            </div>
        </footer>
    </div>

</body>

</html>

users_app/templates/home_doctor.html
{% extends "./base.html" %}

{% block title %} Home page - Doctor {% endblock %}

{% block nav %}
{% include "./nav_doctor.html" %}
{% endblock %}

{% block content %}

{% if user.is_authenticated %}


<div class="row">
    <nav class="navbar navbar-light">
        <div class="container-fluid">
            <span class="navbar-brand h1">Hello {{ doctor_name }}</span>
        </div>
    </nav>
</div>

<div class="row">

    <div class="btn-group" role="group">
        <div class="col">
            <button type="button" class="btn btn-success float-start btn-lg" id="btnPreviousWeek">&#x3c;&#x3c; Previous
                Week</button>
        </div>

        <div class="col">
            <button type="button" class="btn btn-success float-end btn-lg" id="btnNextWeek"> &ensp; &ensp;Next Week
                &#x3e;&#x3e;</button>
        </div>
    </div>

</div>



<div class="row">

    <table class='table' id='table_calendar'></table>
</div>

<!-- Adopted from https://getbootstrap.com/docs/5.0/components/modal/ -->
<!-- Modal window-->
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex=">
    aria-labelledby=" staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <form action="None" method="post" name="modalForm">
            {% csrf_token %}
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalFormTitle">Title_none</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal_body">
                    No text
                </div>
                <!-- Textarea for entering symptoms -->
                <div class="modal-body" id="modal_symptoms">
                </div>
                <div class="modal-footer" id="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close window</button>
                    <input type="hidden" name="doctor" value={{ doctor_id }} />
                    <button type="submit" class="btn btn-primary" id="modalFormSubmitButton">None</button>
                </div>
            </div>
        </form>
    </div>
</div>


<!-- A JavaScript date library for parsing, validating, manipulating, and formatting dates. -->
<script src="https://cdn.jsdelivr.net/npm/moment@2.29.4/moment.min.js"></script>



<script>

    // Table cell onClick event listener
    function onCellClick(e) {

        const cell = e.target.closest('td');

        // store the colour of the current cell
        colour_cell = '';


        if (!cell) {
            return;
        }

        if (cell.className == 'table-success') {
            console.log("Green cell");
            colour_cell = 'green';

        } else if (cell.className == 'table-secondary') {
            console.log("Gray cell");
            return;
        } else if (cell.className == 'table-danger') {
            console.log("Red cell - no booking possible");
            return;

        } else if (cell.className == 'table-warning') {
            console.log("Yellow cell - not confirmed appointment");
            colour_cell = 'yellow';

        } else if (cell.className == 'table-info') {
            console.log("Light Blue cell - confirmed");
            colour_cell = 'light_blue';

        } else {
            console.log("onCellClick - cell has no colour or colour is unknown.");
            return;
        }

        // reading date and time from data-date attribute
        const data_date = cell.dataset.date;

        //reading patient name from data-patient_name
        const data_patient_name = cell.dataset.patient_name;

        //reading patient name from data-patient_id
        const data_patient_id = cell.dataset.patient_id;

        //reading symptoms from data-symptoms
        const data_symptoms = cell.dataset.symptoms;

        // get body element from the modal dialog and add text
        const mbody = document.getElementById('modal_body');
        mbody.innerHTML = '<h6>' + data_patient_name + '</h6>' + '<p>' + data_date + '</p>';

        // Adding appointment date and time as a hidden input to be sent to the server
        const modalfooter = document.getElementById('modal-footer');
        modalfooter.innerHTML += "<input type='hidden' id='appointment_date' name='appointment_date' value= " + "'" + data_date + "'" + " />";

        // Adding patient_id as a hidden input to be sent to the server
        modalfooter.innerHTML += "<input type='hidden' id='patient_id' name='patient' value= " + "'" + data_patient_id + "'" + " />";

        // depending on the cell colour we define the behaviour of the modal window
        if (colour_cell == 'yellow') {

            // patient can book an appointment for the green timeslots 
            document.modalForm.action = "{% url 'appointments_app:confirm_appointment' %}";
            const submit_button = document.getElementById('modalFormSubmitButton');
            submit_button.innerText = 'Confirm';

            // update modal window title
            const form_title = document.getElementById('modalFormTitle');
            form_title.innerText = 'Confirm appointment?';

            // add symptom text box with a lable  
            const msymptoms = document.getElementById('modal_symptoms');
            msymptoms.innerHTML = "<h6>Symptoms: </h6>";
            msymptoms.innerHTML += "<textarea readonly id='symptoms' name='symptoms' rows='4' cols='44' >" + data_symptoms + "</textarea>"

        } else if (colour_cell == 'blue') {

            // patient can cancel the appointment for the blue timeslots

            // update the url in the form to one that allows to cancel an appointment 
            // and update modal window labels 
            document.modalForm.action = "{% url 'appointments_app:cancel_appointment' %}";
            const submit_button = document.getElementById('modalFormSubmitButton');
            submit_button.innerText = 'Cancel Appointment';

            //update title of modal window
            const form_title = document.getElementById('modalFormTitle');
            form_title.innerText = 'Cancel appointment?';

        } else {
            console.log('onCellClick -- Error something wrong colour is not defined. ');
            return;
        }

        var myModal = new bootstrap.Modal(document.getElementById('staticBackdrop'), {
            keyboard: false
        });

        // show modal window
        myModal.show();
    };

    // this is called as a callback to assign event listeners for html-table cells
    function addEventListeners() {

        const day_columns = document.getElementsByClassName('table table-hover one-day-column');

        for (var i = 0; i < day_columns.length; i++) {
            day_columns[i].addEventListener("click", onCellClick);
        }
    };



</script>

<script>

    // update week calendar  
    function update_calendar(doctor_id, year, week_number, mycallback) {
        const request = new XMLHttpRequest();
        request.open('GET', '/appointment/calendar/' + doctor_id + '/' + year + '/' + week_number + '/');
        request.send();

        request.onload = function () {
            if (request.status == 200) {
                let table = document.getElementById('table_calendar');
                table.innerHTML = request.response;
                mycallback();
            }
        };

        return true;
    };

    // return a number of isoweeks in the sent year
    function get_number_of_weeks(year) {

        const year_js = moment().year(year);
        return year_js.weeksInYear();
    };

    // increment week number by one and update calendar
    function increment_week_number() {

        year = parseInt(sessionStorage.getItem("year"), 10);
        week_number = parseInt(sessionStorage.getItem("week_number"), 10);

        week_number += 1;

        const number_of_weeks = get_number_of_weeks(year);

        if (week_number > number_of_weeks) {

            // if the incremented week does not exist in the current year then we need to switch
            // to the first week of the next year

            year += 1;
            sessionStorage.setItem("year", year);

            week_number = 1;
        }

        sessionStorage.setItem("week_number", week_number);

        update_calendar({{ doctor_id }}, year, week_number, addEventListeners);

    return true;
    };

    // decrement week number by one and update calendar
    function decrement_week_number() {

        year = parseInt(sessionStorage.getItem("year"), 10);
        week_number = parseInt(sessionStorage.getItem("week_number"), 10);


        // special care needs to be taken when the current week is one and we are going to decrement this
        if (week_number == 1) {

            // we need to decrement the year as week 0 does not exist
            year -= 1;

            //we need to check how many weeks are in the decremented year
            let number_of_weeks = get_number_of_weeks(year);

            // and assign this number to the week counter
            week_number = number_of_weeks;

        } else {

            // just decrement when we are no in the edge
            week_number -= 1;

        }

        sessionStorage.setItem("year", year);
        sessionStorage.setItem("week_number", week_number);

        update_calendar({{ doctor_id }}, year, week_number, addEventListeners);

    return true;
    };

</script>

<script>

    // store the original values for year and week_number passed into the template    
    sessionStorage.setItem("year", {{ year }});
    sessionStorage.setItem("week_number", {{ week_number }});


    // declaration for the event listener for Next week button
    document.getElementById("btnNextWeek").addEventListener("click", function () {

        increment_week_number();

        // https://stackoverflow.com/questions/72494154/a-listener-indicated-an-asynchronous-response-by-returning-true-but-the-messag
        return true;

    });


    // declaration for the event listener for Previous week button
    document.getElementById("btnPreviousWeek").addEventListener("click", function () {

        decrement_week_number();

        // https://stackoverflow.com/questions/72494154/a-listener-indicated-an-asynchronous-response-by-returning-true-but-the-messag
        return true;

    });

</script>


<script>

    document.onload = update_calendar({{ doctor_id }}, {{ year }}, {{ week_number }}, addEventListeners);

</script>

{% endif %}

{% endblock %}

users_app/templates/home_patient.html
{% extends "./base.html" %}
{% block title %} Home page - Patient {% endblock %}

{% block nav %}
{% include "./nav_patient.html" %}
{% endblock %}


{% block content %}

{% if user.is_authenticated %}


<div class="row">

    <!-- As a heading -->
    <nav class="navbar navbar-light ">
        <div class="container-fluid">
            <p class="navbar-brand mb-1 h1">Hello {{ user.username }} </p>
        </div>
    </nav>

</div>

<div class="row">

    <div class="col">

        <!-- As a heading -->
        <div class="col">
            <nav class="navbar navbar-light ">
                <div class="container-fluid">
                    <span class="navbar-brand mb-1 ">List of upcoming and previous appointments.</span>
                </div>
            </nav>

        </div>

        <table class="table table-success table-striped">
            <thead>
                <tr>
                    <th scope="col">Appointment Date</th>
                    <th scope="col">Doctor</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for appointment in appointments %}
                <tr>
                    <td>{{ appointment.appointment_date|date:"d/m/Y H:i"}}</td>
                    <td>Dr. {{ appointment.doctor.user.last_name }}</td>
                    <td>{{ appointment.appointment_status }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- Wish List -->
    <div class="col">
        <nav class="navbar navbar-light ">
            <div class="container-fluid">
                <span class="navbar-brand mb-1 ">Wish list</span>
            </div>
        </nav>


        <table class="table table-success table-striped">
            <thead>
                <tr>
                    <th scope="col">Appointment Date</th>
                    <th scope="col">Doctor</th>
                    <th scope="col">Status</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for entry in wishlist %}
                <tr>
                    <td>{{ entry.appointment_date|date:"d/m/Y H:i" }}</td>
                    <td>Dr. {{ entry.doctor.user.last_name }}</td>
                    <td>{{ entry.wishlist_status }}</td>

                    {% if entry.wishlist_status.status == "Available" %}

                    <td>
                        <form action="{% url 'appointments_app:book_appointment' %}" method="post">
                            {% csrf_token %}

                            <input type="hidden" name="doctor" value="{{ entry.doctor.pk }}" />
                            <input type="hidden" name="appointment_date"
                                value="{{ entry.appointment_date|date:'c' }}" />
                            <input type="hidden" name="symptoms" value='{{ entry.symptoms }}' />

                            <button type="submit" class="btn btn-primary">Book</button>

                        </form>

                    </td>

                    {% else %}
                    <td></td>
                    {% endif %}

                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endif %}

{% endblock %}

users_app/templates/login.html
{% extends "./base.html" %}

{% block title %} Login {% endblock %}

{% block nav %}
{% include "./nav_patient.html" %}
{% endblock %}

{% block content %}

    {% if messages %}

        {% for message in messages %}

            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}

                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>

            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}

                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>

            {% endif %}

        {% endfor %}

    {% endif %}

<h3>Login page</h3>

<div class="row">

    <div class="col">
    </div>

    <div class="col">

        <form method="post">

            {% csrf_token %}

            {% for field in login_form %}
            <p>
            <div class="form-group">
                {{ field.label_tag }} <br>
                {{ field }}
            </div>
            </p>
            {% endfor %}
            <button type="submit">Log in</button>

        </form>
    </div>

    <div class="col">
    </div>
</div>

{% endblock %}

users_app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">

        <a class="navbar-brand" href="#">AOBS</a>

        

        {% if user.is_authenticated %}
        <a href="/">Home</a> |
        <a href="{% url 'appointments_app:doctor_list_view' %}">Book appointment</a> |        
        <a href="{% url 'users_app:logout_page' %}">Logout</a> |
        {% else %}
        <a href="">Register</a> |
        <a href="{% url 'users_app:login_page' %}">Login</a> |
        {% endif %}

    </div>

</nav>

users_app/templates/nav_doctor.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">

        <a class="navbar-brand" href="#">OABS</a>        

        {% if user.is_authenticated %}
        <a href="{% url 'users_app:home_page' %}">Home</a> |
        <a href="{% url 'appointments_app:request_daysoff' %}">Days off</a> |        
        <a href="{% url 'users_app:logout_page' %}">Logout</a> |
        {% else %}
        <a href="">Register</a> |       
        {% endif %}

    </div>

</nav>

users_app/templates/nav_patient.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="container-fluid">

        <a class="navbar-brand" href="#">OABS</a>        

        {% if user.is_authenticated %}
        <a href="{% url 'users_app:home_page' %}">Home</a> |
        <a href="{% url 'appointments_app:doctor_list_view' %}">Book appointment</a> |        
        <a href="{% url 'users_app:logout_page' %}">Logout</a> |
        {% else %}
        <a href="{% url 'users_app:registration_page' %}">Register</a>        
        {% endif %}

    </div>

</nav>

users_app/templates/nav_registration.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">OABS</a>       
        <a href="{% url 'users_app:login_page' %}">Login</a> 
    </div>
</nav>

users_app/templates/registration.html
{% extends "./base.html" %}

{% block title %} Registration {% endblock %}

{% block nav %}
{% include "./nav_registration.html" %}
{% endblock %}

{% block content %}

<h3>Registration page</h3>

<div class="row">

    <div class="col">
    </div>

    <div class="col">

        <form method="post">
            
            {% csrf_token %}

            {% for field in registration_form %}
            <p>
            <div class="form-group">
                {{ field.label_tag }} <br>
                {{ field }}
            </div>
            </p>
            {% endfor %}
            <button type="submit">Sign up</button>

        </form>
    </div>

    <div class="col">
    </div>
</div>


{% endblock %}